name: pnm
dependencies:
    - python=3.9
    - pip
    - pip:
      - numpy==1.20.0
      - porespy==1.3.1
      - matplotlib==3.5.1
      - openpnm==2.8.2
      - scipy==1.7.3
      - scikit-image==0.18.0
      - pandas==1.3.5
